### ISSUE TITLE
Nested Reform objects do not have a reference to parent/sibling forms.

### ISSUE THREAD

**Issue by atistler** [trailblazer/reform#428] opened 2017-04-10 01:06 UTC
Hi, i am trying to validate a property inside of a collection (inner_value) based on a property outside that collection (outer_value).  I am not sure it is possible since the inner_value form object does not have a reference to its parent.  This is more of a feature request, than an actual issue.  The request is that nested form objects have a reference to their parent form objects and in the collection case, also a reference to their siblings.  This would allow for contextual validation.

```
class MyForm1 < Reform::Form
  property :outer_value
  collection :col, populator: ->(collection:, index:, **) { collection.insert(index, OpenStruct.new) } do
    property :inner_value
    validate do
      if inner_value != ?.outer_value
        errors.add(:base, 'inner_value does not match outer_value')
      end
    end
  end
end
```

`?` in this case is my 'missing reference'

```
form = MyForm1.new(OpenStruct.new(col: []))
form.validate(outer_value: 'a', col: [{ inner_value: 'a' }])
```

If i inspect self inside of the validation i get:
```
 => #<#<Class:0x007fe0952a07b0>:0x007fe0952799d0
 @_changes={"inner_value"=>true},
 @errors=
  #<Reform::Form::ActiveModel::Errors:0x007fe0952793e0
   @base=
    #<#<Class:0x007fe0952a07b0>:0x007fe0952799d0
     @_changes={"inner_value"=>true},
     @errors=#<Reform::Form::ActiveModel::Errors:0x007fe0952793e0 ...>,
     @fields={"inner_value"=>"a"},
     @mapper=#<#<Class:0x007fe095279890>:0x007fe0952796b0 @model=#<OpenStruct>>,
     @model=#<OpenStruct>>,
   @details={},
   @messages={}>,
 @fields={"inner_value"=>"a"},
 @mapper=#<#<Class:0x007fe095279890>:0x007fe0952796b0 @model=#<OpenStruct>>,
 @model=#<OpenStruct>>
```

In TBR chat it was suggested that I pass self to my `model` during population, which in this case is an OpenStruct, however this would in most cases be an AR model or something that should not have a reference to the form.

```
class MyForm1 < Reform::Form
  property :outer_value
  collection :col, populator: ->(collection:, index:, **) { collection.insert(index, OpenStruct.new(base: self)) } do
    property :inner_value
    validate do
      if inner_value != self.model.base.outer_value
        errors.add(:base, 'inner_value does not match outer_value')
      end
    end
  end
end
```

**Comment by atistler** [comment] 2017-04-10 01:46
I found that Disposable::Twin::Parent is what i need however since `property` is private it does not work:

```
require 'disposable/twin/parent'

[4] pry(main)> class MyForm1 < Reform::Form
[4] pry(main)*   feature Parent
[4] pry(main)*   property :outer_value
[4] pry(main)*   collection :col, populator: ->(collection:, index:, **) { collection.insert(index, OpenStruct.new) } do
[4] pry(main)*     property :inner_value
[4] pry(main)*     validate do
[4] pry(main)*       if inner_value != self.parent.outer_value
[4] pry(main)*         errors.add(:base, 'inner_value does not match outer_value')
[4] pry(main)*       end
[4] pry(main)*     end
[4] pry(main)*   end
[4] pry(main)* end
NoMethodError: private method `property' called for MyForm1:Class
Did you mean?  properties
from /Users/atistler/.rvm/gems/ruby-2.3.1@iac-pipeline/gems/disposable-0.4.2/lib/disposable/twin/parent.rb:3:in `included'
```

Changing parent.rb to:

```
module Disposable::Twin::Parent
  def self.included(includer)
    includer.send(:property, :parent, virtual: true)
  end

  # FIXME: for collections, this will merge options for every element.
  def build_twin(dfn, value, options={})
    super(dfn, value, options.merge(parent: self))
  end
end
```

allow this to work.

**Comment by fran-worley** [comment] 2017-04-10 09:39
Thanks for raising this, you got to the solution before I could get back to you.

I'm going to close this as a duplicate of https://github.com/apotonick/disposable/issues/61
A PR in disposable to fix this would be awesome!

**Closed by fran-worley** 2017-04-10 09:39 UTC
