### ISSUE TITLE
Subsequent calls of #validate do not revalidate the form

### ISSUE THREAD

**Issue by tilod** [trailblazer/reform#282] opened 2015-07-29 11:48 UTC
After #validate is called with invalid values, any subsequant calls of #validate on the same form instance will also return `false` even when valid params are passed. The `#errors` are not reset either. However, the new params are correctly assigned to the properties in the form.

``` ruby
Profile = Struct.new(:name)
class ProfileForm < Reform::Form
  property :name
  validates :name, presence: true
end

f = ProfileForm.new(Profile.new)
f.validate(name: '')         # => false
f.name                       # => ""
f.errors.full_messages       # => ["Name muss ausgefüllt werden"]

f.validate(name: 'test')     # => false
f.name                       # => "test"
f.errors.full_messages       # => ["Name muss ausgefüllt werden"]
```

The opposite way (calling with valid params first and invalid params second) works: The first call of `#validate` returns `true`, the second `false`.

``` ruby
f2 = ProfileForm.new(Profile.new)
f2.validate(name: 'test')    # => true
f2.name                      # => "test"
f2.errors.full_messages      # => []

f2.validate(name: '')        # => false
f2.name                      # => ""
f2.errors.full_messages      # => ["Name muss ausgefüllt werden"]
```

The readme doesn't state the behaviour of calling `#validate` multiple times. But I would expect it to revalidate the form and also reset the `#errors`.

**Comment by apotonick** [comment] 2015-07-29 18:02
This is not supported by Reform. My initial API was

```ruby
res, errors = Album::Form.validate(album).(params)
```
to make it functional and state-less. Remember, a Reform object is not a long-living object like all the other Rails objects (models, controllers). A form basically has one purpose: validate an object graph.

Why would you call `validate` twice?

**Comment by tilod** [comment] 2015-07-30 10:51
It's useful for unit testing the validations:

```ruby
let(:params) { Hash[ email: 'test@example.com', password: '12345678' ] }

it 'validates the format of :email' do
  params[:email] = 'blub'
  expect(form.validate(params)).to be false
  expect(form.errors[:email].size).to eq 1

  params[:email] = 'blub@test@example.com'
  expect(form.validate(params)).to be false
  expect(form.errors[:email].size).to eq 1

  params[:email] = 'test@example.com'
  expect(form.validate(params)).to be true

  params[:email] = 'äöü+-_aZ@äöü+-_aZ.de'
  expect(form.validate(params)).to be true
end
```

Of course, I could do one test per input (which would also please the one-expect-per-test-zealots), but I like one test per validation better.

I cannot think of a scenario in production where this could be useful. So it's not a real problem. But it's still inconsistent and surprising behavior.

**Comment by apotonick** [comment] 2015-08-05 07:05
Hm, yeah, I would love to make the API more functional so there is no chance people get this wrong. Maybe in a year, when the Rails-thinking has shifted to a less scripty, more "functional object" one where objects are short-lived and have minimal APIs (that's where I try to get with all my gems).

I don't want to "restrict" users to one #validate call because that's like the horrible DoubleRenderError in Rails. And also, it will introduce even more state.

**Comment by swifthand** [comment] 2015-08-26 20:09
Working with reform for the first time, and I love it. It's a better-thought-out version of an internal tool I have long used, and I hope we can transition all of our form objects over eventually. So first, thank you for making this, @apotonick.

Just wanted to chime in with my experience as it relates to this issue:

After creating my first Reform Form, the first thing I did was fire up a console to play with the public interface a bit, and immediately hit this. If it did not update values or allow re-runs of validate (ala a more strict immutability), that would also have made sense to me, though I would have immediately looked for a way to clone a form to try again. The surprising part was that subsequent calls to validate could actually change values in a manner that resolves an error, but that the error remains.

I think the usage you envision of more temporary, immutable-ish objects is awesome. I also can't imagine I would ever want to call `#validate` twice outside of tests, but I did find that calling `#errors.clear` allows me to issue a second `#validate`. That extra legwork felt acceptable for the narrow/unusual case of ever needing a second validation.

As the person who would know the consequences best, do you know of any danger (e.g. unexpected behavior) in using `form.errors.clear` before re-running `#validate`?

**Comment by apotonick** [comment] 2015-08-27 01:26
Good point, @swifthand about the `errors.clear` even though this is not documented private API. :grin:

It is a hard decision for me because I really want to make the form "immutuable" as it represents more of a workflow that results in one particular state (_"I'm invalid, here are your errors."_) and less of a stateful object that can be reused in the horrible way we use AR models.

**Comment by apotonick** [comment] 2017-02-13 11:11
I'm closing this as revalidation is not a concept supported by Reform and won't be even possible in Reform 3.

**Closed by apotonick** 2017-02-13 11:11 UTC
