### ISSUE TITLE
Type coercion failing when using Form inheritance

### ISSUE THREAD

**Issue by yjukaku** [trailblazer/reform#401] opened 2016-09-16 19:15 UTC
### Complete Description of Issue

Using type coercion in a form, then using a subclass of that Form results in an exception.
### Steps to reproduce
1. Generate new Rails app with a Post model

```
$ rails new TestInheritance
$ cd TestInheritance
$ echo "gem 'reform'" >> Gemfile
$ echo "gem 'reform-rails'" >> Gemfile
$ echo "gem 'dry-types'" >> Gemfile
$ bundle
$ rails g model Post title:string published_at:datetime
$ rails db:migrate
$ mkdir app/forms
```
1. Create `PostBaseForm` with `Coercion` under `app/forms`

``` ruby
class PostFormBase < Reform::Form
  require "reform/form/coercion"
  feature Coercion
  property :title
  property :published_at, type: Types::Form::DateTime
  validates :published_at, presence: true
end
```
1. Create `PostForm` inheriting from `PostBaseForm`

``` ruby
class PostForm < PostFormBase
end
```
1. In the rails console:

```
> PostForm.new(Post.new).validate({published_at: "2016-01-01"})
```
### Expected behavior

The form validates, converting the published_at into a DateTime.
### Actual behavior

Reform throws an exception
### System configuration

**Reform version**: 2.2.1
**Reform Rails version**: 0.1.4
**Rails version**: 5.0.0.1
**Ruby version** 2.3.1p112.
### Full Backtrace of Exception (if any)

```
irb(main):001:0> PostForm.new(Post.new).validate({published_at: "2016-01-01"})
TypeError: no implicit conversion of DateTime into String
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/coercions.rb:17:in `parse'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/coercions.rb:17:in `to_date_time'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/constructor.rb:28:in `[]'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-types-0.8.1/lib/dry/types/constructor.rb:28:in `call'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/disposable-0.3.2/lib/disposable/twin/coercion.rb:20:in `block (2 levels) in coercing_setter!'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/disposable-0.3.2/lib/disposable/twin/coercion.rb:20:in `block (2 levels) in coercing_setter!'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/representable-3.0.0/lib/representable/deserializer.rb:91:in `block in <module:Representable>'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:18:in `evaluate'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:10:in `block in call'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:9:in `each'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:9:in `inject'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/representable-3.0.0/lib/representable/pipeline.rb:9:in `call'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/representable-3.0.0/lib/representable/binding.rb:37:in `uncompile_fragment'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/representable-3.0.0/lib/representable.rb:52:in `block in call'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/representable-3.0.0/lib/representable.rb:50:in `each'
  from /Users/myname/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/representable-3.0.0/lib/representable.rb:50:in `call'


```

**Comment by yjukaku** [comment] 2016-09-16 19:21
It looks like the coercion is happening twice for some reason. The first time, it works correctly, but the second time, it tries to use `.to_date_time` on something that is already a DateTime?

**Comment by johnmeehan** [comment] 2016-09-27 09:15
I'm getting similar with Types::Form::Date.
In this case the method earliest_dispatch_date returns a Date.
```ruby
  property :date_required, type: Types::Form::Date,
    prepopulator: ->(*) { self.date_required = earliest_dispatch_date },
    default:      ->(*) {
      self.date_required = earliest_dispatch_date
    }
```
TypeError: no implicit conversion of DateTime into String

**Comment by yjukaku** [comment] 2016-09-27 15:21
@johnmeehan Is your form also using inheritance?

**Comment by johnmeehan** [comment] 2016-09-27 19:40
yes.  like this:

```ruby
class OrderForm < Reform::Form
  #..universial..stuff..
end
```

```ruby 
class OtherOrderForm < OrderForm
  #...other...stuff...
  property :date_required, type: Types::Form::Date,
    prepopulator: ->(*) { self.date_required = earliest_dispatch_date },
    default:      ->(*) {  self.date_required = earliest_dispatch_date }
end
```

**Comment by fran-worley** [comment] 2018-06-15 07:40
Based on the version of Reform you are using I think this is actually a duplicate of https://github.com/trailblazer/reform/issues/380 which has been resolved in 2.3.0-rc1. If you check against that branch and it is still an issue let us know and I'll reopen this.

**Closed by fran-worley** 2018-06-15 07:40 UTC
