### ISSUE TITLE
Nested dry schema doesn't add error messages to reform result object

### ISSUE THREAD

**Issue by sliminas** [trailblazer/reform#439] opened 2017-06-15 10:46 UTC
I added a test to show the behavior:
https://github.com/sliminas/reform/commit/9724f79f9a01b7dfed869a810498f1382b3784a2
```
1) Failure:
NestedSchemaValidationTest#test_0001_has company error reform/test/validation/dry_validation_test.rb:249]:
--- expected
+++ actual
@@ -1 +1 @@
-{:delivery_address=>{:company=>["must be an integer"]}}
+{}
```

The error messages of the nested address schema for the property delivery_address is not added to the error messages of the form that contains the nested schema.

**Reform version**: 2.3.0rc2

**Comment by zavan** [comment] 2017-06-28 02:06
I discovered that if there's a validation error in the root form, it also validates the nested form.

**Comment by apotonick** [comment] 2017-06-28 02:22
Could you add a test case that provokes this, please? That would help a lot!

**Comment by apotonick** [comment] 2017-06-28 02:23
Ah, you mean it's still invalid, but goes on validating the nested form
instead of stopping? This is per design (second time I say this today haha).

**Comment by zavan** [comment] 2017-06-28 02:40
@apotonick In my case, when using dry-validation, it seems that the nested form validation is simply not called, and code proceeds as if everything is okay, unless there's a validation error in the root form. I'll try to provide you with a test case.

**Comment by zavan** [comment] 2017-06-28 03:02
@apotonick I couldn't reproduce it, [this test](https://github.com/trailblazer/reform/blob/master/test/validation/dry_validation_test.rb) should cover it and it passes, so it's probably a problem in our code. Here are the relevant parts of my code, if you want to check it:

```ruby
# app/concepts/playground/contract.rb - My parent form, all others inherit from it.
require 'reform/form/dry'
require 'reform/form/coercion'

class Playground::Contract < Reform::Form
  feature Dry
  feature Coercion
end
```

```ruby
# app/concepts/depot/operation/create.rb - The operation (the same problem occurs for update).
class Depot::Create < Trailblazer::Operation
  class Present < Trailblazer::Operation
    step Model(Depot, :new)
    step Contract::Build(constant: Depot::Contract::Create)
  end

  step Nested(Present)
  step Contract::Validate(key: :depot)
  step Contract::Persist()
end
```

```ruby
# app/concepts/depot/contract/create.rb - My root form.
class Depot::Contract::Create < Playground::Contract
  property :eri
  property :name

  property :address, form: Address::Contract # Nesting the Address form

  validation with: {form: true} do
    configure do
      def unique_eri?(value)
        query = Depot.where(eri: value)
        query = query.where.not(id: form.model.id) if form.model.persisted?
        query.empty?
      end
    end

    required(:name).filled
    required(:eri, &:unique_eri?)
  end
end
```

```ruby
# app/concepts/address/contract.rb - My nested form, it's validations aren't run.
class Address::Contract < ALM::Contract
  property :street, nilify: true
  property :street_number, nilify: true

  validation do
    required(:street).filled
    required(:street_number).filled
  end
end
```

```ruby
# Gemfile
gem 'cells', '~> 4.1.7'
gem 'cells-rails', '~> 0.0.8'
gem 'cells-slim', '~> 0.0.5'
gem 'dry-types', '~> 0.10.3'
gem 'dry-validation', '~> 0.10.7'
gem 'reform', '~> 2.3.0.rc1'
gem 'reform-rails', '~> 0.2.0.rc1'
gem 'trailblazer', '~> 2.0.6'
gem 'trailblazer-cells', '~> 0.0.3'
gem 'trailblazer-rails', '~> 1.0.2'
```

What happens is what I explained above.

**Comment by zavan** [comment] 2017-06-28 16:24
Update: I do get the errors in `options['contract.default'].errors.messages`:
```ruby
{:"address.street"=>["must be filled"], :"address.street_number"=>["must be filled"]}
```

But it seems that this is not causing validation to fail in the operation, and trailblazer goes on trying to persist it anyway.

**Comment by zavan** [comment] 2017-07-04 18:32
This seems to be a problem with [reform-rails](https://github.com/trailblazer/reform-rails), more specifically [this method](https://github.com/trailblazer/reform-rails/blob/master/lib/reform/form/active_model/validations.rb#L55-L67).

I called `byebug` on my validations and followed the stack, when execution gets to [this point](https://github.com/trailblazer/reform/blob/master/lib/reform/contract/validate.rb#L36) `@result.success?` returns `false`, as it should since there are validation errors. But later, by the time we get to [the method above mentioned](https://github.com/trailblazer/reform-rails/blob/master/lib/reform/form/active_model/validations.rb#L55-L67), `@result.success?` now returns `true`, making trailblazer think all went fine.

**Comment by emaglio** [comment] 2019-07-14 16:26
@apotonick should we move this to reform-rails?

**Comment by emaglio** [comment] 2019-09-07 09:36
A bit late on this bug but better late than never...

@sliminas the problem with your test is that you don't define the nested property so `reform` does not know if it's actually a nested property, check: https://github.com/trailblazer/reform/commit/43578ef6a55ff7915910b30827cad9aea6bdbb43#diff-9f78bc9c4126c088f47ef10bda7f246bR637

@zavan that sounds really weird since TRB simply call `form.validate({}).success?`, this issue quite old so maybe you have already fixed your issue and maybe updated to the latest TRB version?

Gonna close this issue since anyway it might be a `reform-rails` problem

**Closed by emaglio** 2019-09-07 09:36 UTC
Labels: bug, to investigate
